### ISSUE TITLE
idmapped mount: Invalid argument - Failed to change mount attributes

### ISSUE THREAD

**Issue by z59** [brauner/linux#1]
Sorry if this is not the right place to report.
I'm trying idmapped mounts with vanilla kernel 5.15.7. For Ext4/Btrfs mounting works fine, but for SquashFS/OverlayFS results in:
```
Invalid argument - Failed to change mount attributes
```
from strace:
```
syscall_442(0x3, 0x40d983, 0x9000, 0x7ffc139727e0, 0x20, 0) = -1 (errno 22)
```
Maybe I'm doing something wrong.
What is the current status of these filesystems support?
Thanks

**Comment by brauner** [comment]
> Sorry if this is not the right place to report. I'm trying idmapped mounts with vanilla kernel 5.15.7. For Ext4/Btrfs mounting works fine, but for SquashFS/OverlayFS results in:
> 
> ```
> Invalid argument - Failed to change mount attributes
> ```
> 
> from strace:
> 
> ```
> syscall_442(0x3, 0x40d983, 0x9000, 0x7ffc139727e0, 0x20, 0) = -1 (errno 22)
> ```
> 
> Maybe I'm doing something wrong. What is the current status of these filesystems support? Thanks

I have not seen your comment before, sorry. I'm currently working on overlayfs support. It will be a little while longer.
